obj-$(CONFIG_MXC_GPU_VIV_3_14_52) += gpu-viv/
obj-$(CONFIG_MXC_GPU_VIV_3_14_26) += gpu-viv-3.14.26/
obj-$(CONFIG_MXC_IPU_V3) += ipu3/
obj-$(CONFIG_MXC_VPU) += vpu/
obj-$(CONFIG_MXC_HDMI_CEC) += hdmi-cec/
obj-$(CONFIG_MXC_MIPI_CSI2) += mipi/
obj-$(CONFIG_MXC_MLB) += mlb/
obj-$(CONFIG_MXC_SIM) += sim/
